!!ch.sbb.releasetrain.config.model.releasecalendar.ReleaseCalendar
coloumns:
- {name: releaseVersion, 'on': true}
- {name: snapshotVersion, 'on': true}
- {name: maintenanceVersion, 'on': true}
- {name: custom1, 'on': true}
- {name: custom2, 'on': true}
events: []
