!!ch.sbb.releasetrain.config.model.releaseconfig.ReleaseConfig
actions:
- !!ch.sbb.releasetrain.config.model.releaseconfig.JenkinsActionConfig
  enabled: true
  jenkinsBuildToken: test
  jenkinsJobname: test
  jenkinsPassword: 583lgRJGvbBQb+WtJ9wez9P/rn5QNL0r
  jenkinsUrl: www.sbb.ch
  jenkinsUser: matthiasehrsam
  jobAdminMail: ''
  offseMinutes: 0
  properties: {}
- !!ch.sbb.releasetrain.config.model.releaseconfig.EmailActionConfig
  enabled: true
  offseMinutes: 0
  properties: {}
  receiver: t1@a.com,t2@b.com
  sender: test@host.com
  smtpServer: hhh
  subject: hallo
  text: hallo
typ: null
